### ISSUE TITLE
Custom user model with UUID-based id is not usable

### ISSUE THREAD

**Issue by KHIT93** [cnobile2012/django-pam#12]
When using this package together with Django 3.1 and having a custom user model with the id defined like this:
```
id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
```

An error comes just after login, where it complains about the missing `isdigit` attribute

```
Traceback (most recent call last):
  File "/srv/wpaas/lib/python3.6/site-packages/asgiref/sync.py", line 339, in thread_handler
    raise exc_info[1]
  File "/srv/wpaas/lib/python3.6/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/srv/wpaas/lib/python3.6/site-packages/django/core/handlers/base.py", line 231, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/wpaas/lib/python3.6/site-packages/asgiref/sync.py", line 304, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/wpaas/lib/python3.6/site-packages/asgiref/sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "/srv/wpaas/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/wpaas/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 50, in dispatch
    if not request.user.is_authenticated:
  File "/srv/wpaas/lib/python3.6/site-packages/django/utils/functional.py", line 240, in inner
    self._setup()
  File "/srv/wpaas/lib/python3.6/site-packages/django/utils/functional.py", line 376, in _setup
    self._wrapped = self._setupfunc()
  File "/srv/wpaas/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 23, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/srv/wpaas/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/srv/wpaas/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 181, in get_user
    user = backend.get_user(user_id)
  File "/srv/wpaas/lib/python3.6/site-packages/django_pam/auth/backends.py", line 85, in get_user
    or user_data.isdigit()):
AttributeError: 'UUID' object has no attribute 'isdigit'
```

The application which we use django-pam, has a dependency on an external system, which requires the ID of users to be named `id` in the database and also to be of type `uuid`.
Is there some way in the library to get it to work with UUID or would there need to be a fix to handle this?

**Comment by cnobile2012** [comment]
If you look in  `django/contrib/auth/backends.py` you will see that it requires an integer PK. My code just overrides the django code so I cannot accept anything else but a real integer.

I understand what you are doing and it is correct, don't expose the internal PK to an outside API. If you do you leave yourself open to sequential PK attacks. I personally don't use UUIDs I just use 16 to 20 character hashes.

So what to do? When dealing with the API use your UUIDs but when dealing with the DB use the Django generated PKs which are all integers. If you use your UUIDs for everything this issue will not be your last. Many things in Django will fail if you pass it a non-integer where Django expects an integer. The UUIDs should NOT be considered the PKs in your system.
